### PR TITLE
Add note in about deprecation of CRM_Core_Error::fatal

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @MikeyMJCO

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Nice!

**Comment by MikeyMJCO** [comment]
When does the deprecation "hit"?

**Comment by eileenmcnaughton** [comment]
5.28 -

**Comment by MikeyMJCO** [comment]
No harm in merging the docs PR in advance I guess as it's informational rather than new behaviour?

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO we should have been recommending this for years!

**Pull request merged**
