### PR TITLE
Add CIVICRM_MAIL_LOG_AND_SEND

### PR DESCRIPTION
**Pull request by mattwire**
Read this before merging! Two other PRs are required: https://lab.civicrm.org/dev/core/issues/86

### CODE REVIEW

**Comment by monishdeb** [comment]
@seanmadsen  can you please merge this PR?

**Comment by davialexandre** [comment]
Leaving a comment here in case people don't see the comment I left on https://github.com/civicrm/civicrm-core/pull/12037. The actual name is `CIVICRM_MAIL_LOG_AND SEND` and not `CIVICRM_MAIL_LOG_AND_SEND`

**Comment by mattwire** [comment]
@davialexandre see https://lab.civicrm.org/dev/core/issues/86
There are 3 PRs for this

**Comment by seamuslee001** [comment]
Merging as core PRs have been merged

**Pull request merged**
