### PR TITLE
Document civi-test-run script (take 2)

### PR DESCRIPTION
**Pull request by seanmadsen**
This builds on top of #325 and is intended to replace it. 

In #325 Seamus added docs for a new script, `civi-test-run`. 

This PR is different from #325 in the following ways: 

* Use a separate page for `civi-test-run` in the "Tools" chapter
* Point readers to this page so that we can avoid duplicating efforts to describe `civi-test-run`
* Also mention `civi-test-run` in the *list* of all tools
* Don't describe the script's usage. Instead instruct readers to run the script to observe its usage via the command line. (This is to address [comments](https://github.com/civicrm/civicrm-dev-docs/pull/325#issuecomment-328699764) from Tim about how the signature is likely to change in the future)

### CODE REVIEW

**Comment by seanmadsen** [comment]
Would like thoughts from @seamuslee001 @totten before merging

**Comment by totten** [comment]
+1 for moving to its own page.

I've tweaked to mention the `upgrade` and `karma` suites.

**Comment by seanmadsen** [comment]
I like the tweaks, Tim.

I'll merge this on 2017-09-14 if no further comments. 

@seamuslee001 feel free to merge if you approve &mdash; or push more commits or suggest changes.

**Comment by seamuslee001** [comment]
Yep this looks good to me merging

**Pull request merged**
