### PR TITLE
Try and fix link to hook_civicrm_post documentation from the postComm…

### PR DESCRIPTION
**Pull request by seamuslee001**
…it hook documenation

### CODE REVIEW

**Comment by MikeyMJCO** [comment]
The current link is fine and it works...

**Comment by MikeyMJCO** [comment]
https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_postCommit/

**Comment by MikeyMJCO** [comment]
If you're having issues building locally - please make sure you're on the latest stable of MkDocs.

**Comment by seamuslee001** [comment]
sorry @MikeyMJCO wrong place closing this will submit pr for the correct fix

**Pull request closed without merging**
