### PR TITLE
CRM-20238 - Add documentation for hook_civicrm_inboundSMS

### PR DESCRIPTION
**Pull request by ineffyble**
Documentation to support PR to add new hook for inbound SMS.

~Code PR: https://github.com/civicrm/civicrm-core/pull/9962~
***Edit**: code PR has changed to: https://github.com/civicrm/civicrm-core/pull/10347*

### CODE REVIEW

**Comment by seanmadsen** [comment]
This looks cool, @ineffyble. I think it'd be best to wait until the core PR is merged before we merge this docs PR. (Note that the plan is to eventually have the Developer Guide live within CiviCRM core so that your two PRs could be one. This will probably happen after we're done migrating content into the Dev Guide from the wiki.)

In the mean time, would you like to finish the sentence "Using this hook you can..." in the Notes section? Or maybe just remove the Notes section entirely? Great examples, by the way! Also, is it just me or is `$escapedFrom` uninitialized in your last example?

**Comment by seanmadsen** [comment]
@michaelmcandrew I saw this and thought of you, given your work on Chained SMS. 

@ineffyble You might get a kick out of Michael's extension [Chained SMS](https://github.com/3sd/io.3sd.chainedsms) which gives automated replies to incoming SMS messages

**Comment by ineffyble** [comment]
Huh, I wonder if my last revisions didn't get saved - I thought I'd removed that Notes section (and I thought I'd changed the escapedFrom).

Will update it - there's discussion in core PR about refactoring, so I may need to update this one with new docs in any case.

**Comment by seamuslee001** [comment]
@ineffyble are you able to update this based on the updated style of the hook?

**Comment by seanmadsen** [comment]
@ineffyble I see that https://github.com/civicrm/civicrm-core/pull/10347 was merged. Great! It looks like we're waiting on you provide some updates to this documentation before we can publish it. Can you help finish `hook_civicrm_inboundSMS` by documenting it?

**Comment by ineffyble** [comment]
Apologies for the delay, I've been absolutely swamped recently. Thank you heaps to @seamuslee001 for picking up my slack and updating this PR.

**Comment by seamuslee001** [comment]
@seanmadsen @ineffyble Documentation should be updated now

**Comment by seanmadsen** [comment]
Great! Thanks @seamuslee001! :slightly_smiling_face:

**Pull request merged**
