### PR TITLE
Issue #498 - a bunch of broken reference fixes

### PR DESCRIPTION
**Pull request by xurizaemon**
Inspired by a nudge on civicrm-user-guide#191, thanks @joannechester :grinning:

### CODE REVIEW

**Comment by seamuslee001** [comment]
@xurizaemon why are you stripping out the .md they should be there i would have thought @seanmadsen

**Comment by xurizaemon** [comment]
Try it. The first change in the commit is on https://docs.civicrm.org/dev/en/latest/extensions/ - search for " Civix Documentation", click the link, 404. I've tested *most* of these locally using mkdocs.

I found them by crawling https://docs.civicrm.org and looking for "broken link" so these should all be legit broken links discovered on the live site.

Doing a second similar issue for user docs now.

It's possible this could be done in nginx / apache instead, so that the docs links work on Github as well ... is that the intent? Currently it seems like only a few links are broken, and I hope this is an improvement.

**Comment by joannechester** [comment]
Something very odd is happening here. 
@xurizaemon  You are s indicating that you needed to remove the .**md** from the middle line of the following to get the link to work:
  -   [hook_civicrm_navigationMenu](/hooks/hook_civicrm_navigationMenu.md) manipulates the navigation bar at the top of every screen
    -   [hook_civicrm_alterMenu](/hooks/hook_civicrm_alterMenu.md) manipulates the list of HTTP routes (using PHP arrays)
    -   [hook_civicrm_xmlMenu](/hooks/hook_civicrm_xmlMenu.md) manipulates the list of HTTP routes (using XML files)
( lines 12-14 of docs/hooks/hook_civicrm_navigationMenu.md)

All three links work for me as is.   

However, I when I checked one of your prop0sed changes ( can't remember which :( ) I did get a 404 error.

**Comment by joannechester** [comment]
I have found an error that I can replicate and I think the issue is the trailing slash not the .md.
Line 21 of docs/extensions/index.md 

`>  Install ***civix v14.01*** or newer. For instructions, see [Civix Documentation](/extensions/civix.md/). This page assumes that "civix" is installed and registered in the PATH.`

Should be just `[Civix Documentation](/extensions/civix.md)`  I think

**Comment by xurizaemon** [comment]
Nice one, I'll take another look. Cheers!

**Comment by seanmadsen** [comment]
@xurizaemon would you be willing to revisit this PR with these [internal link standards](https://docs.civicrm.org/dev/en/latest/documentation/markdown/#internal-url-standards) in mind?

**Comment by seanmadsen** [comment]
@xurizaemon I'm closing this for now, but I'm happy to re-open if you want to come back to it

**Pull request closed without merging**
