### PR TITLE
Add link to Abandoned Extensions page/info.

### PR DESCRIPTION
**Pull request by MikeyMJCO**

### CODE REVIEW

**Comment by twomice** [comment]
This mentions "process for adopting", which is great. Could we add a little meaning by saying "process for adopting or otherwise addressing" ?

**Comment by MikeyMJCO** [comment]
Commit pushed.

**Comment by twomice** [comment]
Thanks @MikeyMJCO

**Comment by MikeyMJCO** [comment]
Gonna merge this one now then :-)

**Pull request merged**
