### PR TITLE
Add documentation for WP REST API wrapper

### PR DESCRIPTION
**Pull request by kcristiano**
required by https://github.com/civicrm/civicrm-wordpress/pull/160

### CODE REVIEW

**Comment by MikeyMJCO** [comment]
This needs to go under the v3 folder I would guess?

**Comment by MikeyMJCO** [comment]
Then if/when a v4 implementation is released that should be documented separately as v4/wp-rest.md

**Comment by kcristiano** [comment]
@MikeyMJCO I was conflicted on placement.  Technically yes it might belong under v3, but it's CMS specific so I created a new folder.   I am OK with moving and defer to you for placement.

**Comment by MikeyMJCO** [comment]
I'd say put it in as `api/v3/wp-rest.md` - I'm okay with CMS specific stuff in there :-) I think we should link to it then as well from `api/vp/interfaces.md`

**Comment by kcristiano** [comment]
@MikeyMJCO I moved the file to `/docs/api/v3/wp-rest.md` and took a crack at `interfaces.md`   Looks like I have some white space cleanup that snuck in .  let me know if you wnat me to revert that commit.

**Comment by MikeyMJCO** [comment]
I'm good with this - thanks for the free whitespace cleanup :-D

**Pull request merged**
