### PR TITLE
Update planning.md

### PR DESCRIPTION
**Pull request by dvhirst**
Reading for content; editing for consistency. 
Updated per seamuslee001's comment, and I found another missed edit in the automate testing paragraph.

### CODE REVIEW

**Comment by seamuslee001** [comment]
This looks ok to me but would like @seanmadsen just to do a review of this before merging

**Comment by dvhirst** [comment]
Noted, no problems for me.

**Comment by seanmadsen** [comment]
:+1:

**Comment by dvhirst** [comment]
Thanks.

**Pull request merged**
