### PR TITLE
Create hook_civicrm_alterAngular.md

### PR DESCRIPTION
**Pull request by colemanw**
See https://github.com/civicrm/civicrm-core/pull/10085
@totten I've added docs for this hook.

### CODE REVIEW

**Comment by totten** [comment]
Good idea adding a page under "Hooks".

FWIW, there's also this page: https://docs.civicrm.org/dev/en/latest/framework/angular/changeset/ 

At the moment, the pages are pretty similar, but the ambition in `framework/angular/changeset` was to also talk about the workflow with the helper commands

```
cv ang:html:list
cv ang:html:show <file>
cv ang:html:show <file> --diff
```

**Comment by totten** [comment]
@colemanw I suggest hyperlinking between the pages and then merging.

**Comment by seanmadsen** [comment]
@colemanw also run `./bin/hook-summary.py` to re-generate the hooks summary page based on the content of your hook file.

**Comment by colemanw** [comment]
@seanmadsen I've updated the pages per @totten's suggestion. Could you please check to see if I did the hyperlinks correctly?
I tried running the python script but it didn't do anything. It ran but gave no output and did not update the summary.md file :/ Might be a problem with python on my system?

**Comment by seanmadsen** [comment]
@colemanw 

> the python script but it didn't do anything

That's because the hook needed to be added to the menu (`mkdocs.yml`) first. (The python script reads from the menu file to generate the page.)

I modified the menu to add the hook. I also tweaked the hook description and regenerated the summary page. I think we're good to go here, so I'm merging.

**Pull request merged**
