### PR TITLE
Add more links to the APIv4 example extension

### PR DESCRIPTION
**Pull request by colemanw**
Makes the example extension easier to find from the API Architecture page.

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks @MikeyMJCO for the lightning fast merge :)

**Comment by MikeyMJCO** [comment]
No build yet though... :-/

**Comment by MikeyMJCO** [comment]
I gave it a manual poke for a build :-)

**Comment by colemanw** [comment]
Looks good

**Pull request merged**
