### PR TITLE
Resolve #577 Fix URL pointing to how to set up extension directory

### LINKED ISSUE #577: Self-referential link on page is confusing
3rd bullet point under "Extensions" header has a broken link:

"For instructions, see Extensions."

It's trying to link to this page:

https://github.com/civicrm/civicrm-dev-docs/blob/master/extensions/index.md

What's worse is that the link appears to be attempting to access the exact same page it's on, rendering it useless even if it did work.

On a general note, this is the 3rd broken link and 2nd confusing statement that I've come across in 5 minutes of trying to read up on Civi extension building.  The state of this documentation set is terrible.

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @MegaphoneJon @jptillman 

This points the documentation to the correct place for creating the Extensions directory which is in the Sysadmin guide not developer

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
make sense - I can't merge, but it goes from relative url to non- relative too - other urls are relative?

**Comment by seamuslee001** [comment]
@eileenmcnaughton yes because the sys-admin guide is in a separate repo to this the other urls reference content within the devdocs repo as per the styleguide https://docs.civicrm.org/dev/en/latest/documentation/style-guide/#urls https://docs.civicrm.org/dev/en/latest/documentation/markdown/#external-hyperlinks https://docs.civicrm.org/dev/en/latest/documentation/markdown/#internal-url-standards

**Comment by eileenmcnaughton** [comment]
ok sure - if you have merge rights here I endorse you merging it - otherwise will need to wait for one of the others

**Comment by seamuslee001** [comment]
Merging as per approval from @eileenmcnaughton

**Pull request merged**
