### PR TITLE
(WIP) Add specific criteria for PR review

### PR DESCRIPTION
**Pull request by seanmadsen**
## Before

The steps to review a core PR give the reviewer quite a bit of leeway to "form an opinion about the fix" without very much guidance on how people should be forming those opinions. 

## After

Developers can use the following template when reviewing a core PR

* [ ] It's a worthy pursuit.
* [ ] It works as advertised.
* [ ] It makes sense for all users.
* [ ] It's unlikely to surprise users.
* [ ] New code is readable and makes sense.
* [ ] It doesn't appear to introduce security vulnerabilities.
* [ ] Acceptance criteria are either: (a) not stated, or (b) met.
* [ ] Significant new functionality is either: (a) not present, or (b) covered by new unit tests. 
* [ ] New documentation is either: (a) not needed, or (b) provided within this PR, or (c) provided in a separate PR which already exists.

## Notes

This PR would be somewhat of a policy change (not just a docs improvement), and as such, I would want approval from people like @totten @eileenmcnaughton @seamuslee001 (and maybe others &mdash; not sure what the protocol is for making decisions like this). 

This was just an idea I had. I won't push it. Very much open to swiftly closing this PR if others are not interested in it!

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I think this

" It makes sense for all users." should probably be for all users who may be affected

"It's unlikely to surprise users." is an interesting one  - perhaps it should be confuse as in "what a wonderful surprise" doesn't sound like a reason not to merge

I try to enforce a higher standard than above about code quality & tests. ie. I generally think PRs should improve code quality and 'not-worse' is a fall-back position. I think tests should be required for bug fixes and any improvement as a starting point and I make exceptions from there. Exceptions might depend on the code are - ie. an change to post submit functionality on contribution, membership or event forms or the api or search code, or import, or dedupe  code without a unit test would have a lot of pressure on it to have a unit test. Something like reports I expect to start pushing harder on.

However, I would only push a code submitter to provide a test if I felt it was appropriate to where that reviewer is on their path to contributing to CiviCRM. (If they don't I would either waive or do the test myself). I also think we give up our opportunity to push people to submit tests if we don't give timely feedback on their PRs (this is a big issue). There are some things that are very hard to write unit tests for, in which case the return on writing them is low & I would consider that. In addition there are layers that are not covered by unit tests.

This is all to respond to the detail. I'm ho-humming about the idea of a checklist. I guess it feels a bit rote - but I need to think more about whether there is any downside to it

**Comment by totten** [comment]
Similar list from earlier this year: https://docs.google.com/document/d/1ttpSbNNkg5FRQb4_u9W1Av-oRCTViVdniiLbaQsv71A/edit#heading=h.45zmkk714nfq

Considerations on writing the list of criteria (checkboxes/questions/prompts/guidelines):
 * _Detailed, objective_ review-criteria will probably lead to a long list. 
 * _Open-ended, subjective_ review-criteria might allow for a short list.
 * Detailed questions can be clearer and easier to answer.
 * Detailed questions are often irrelevant/beside the point. (A bunch of Q's about CSS or styling would be irrelevant to a schema change.) Mitigating this adds complexity.
 * With open questions, you can help bring the reviewer back into the mindset of a general consumer/reader. (This could help counteract the impulse many reviewers have to accept the original author's framing?)
 * With open questions, you miss a lot of the little gotchas that experience teaches us.

Considerations on the mechanism/process for handling the criteria:
 * Github allows you to provide PR templates with checklists, but Github's permission-model is unworkable.  (I'm pretty sure Gitlab has the same limitations.)
 * Having the reviewer copy/paste seems like a nice, simple, lo-tech approach.
   * This requires more proof-of-work for the reviewer, which will actually be reassuring to other readers -- but it may feel excessive for small changes.
   * (Technical add-on/gilding: bookmarklet to copy in the list -- so that you don't have to manually look up the page and copy/paste)
 * Another nice, simple, lo-tech approach: just have the reviewer *read* the list -- then they can post a reaction.
   * This requires less effort from the reviewer, but provides less proof-of-work.
   * This allows you to have a longer list. (The reviewer can skip sections based on relevance.)
   * (Technical add-on/gilding: use PR-template or a buildbot to include a link in the PR's discussion -- so that it's always in-your-face during code-review)
 * A more techy/gilded approach: write the criteria as an HTML form with some checkboxes/inputs. At the bottom, have a "Copy to Clipboard" button. 
   * (Aside: There's gotta some kind of tooling already that could support a workflow like bookmarklet=>webform=>coded-url  for filling out a questionnaire/review-form -- some variation on a Loomio or Webform or SurveyMoney or somesuch...)

**Comment by eileenmcnaughton** [comment]
I guess  have a generalised feeling that this would not improve the quality of review but would improve the ability of other people to 'peer over your shoulder'. 

The thing I'm trying to figure out is whether having this would cause me to simplify the thought process I go through when reviewing / considering a change - in a way that would actually be less constructive. ie. would I simply check the 'is a worthy pursuit' check box & move on this were in place  rather than the much more nuanced, but harder to articular & less transparent process I go through now.

**Comment by eileenmcnaughton** [comment]
Or perhaps if I step back from being the reviewer & look at making the decision 'do I merge something that someone else has reviewed ' would I just look at whether the reviewer says it ticks the boxes & click merge.

I remain on the fence :-)

**Comment by seanmadsen** [comment]
There has been a much larger discussion about the core PR review process that began before I submitted this suggestion to use a checklist. I wasn't aware of the larger discussion and probably would not have submitted this PR had I known others were talking about this stuff more intensively. I still think a checklist is a cool idea, but I'm closing this PR because at this point I doubt we'll use *this* as the basis for future PR review policies. We can still refer to this after it's closed.

**Pull request closed without merging**
