### PR TITLE
Document BuildKit EoL Policy

### PR DESCRIPTION
**Pull request by MikeyMJCO**
Implements discussion which took place in civicrm/civicrm-buildkit/issues/432

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO so I find this confusing as a mac & occassionally windows buildkit user. It implies there is no support for either. For windows I have only used in vagrant so that might be true but for Mac there are no obvious support issues

**Comment by MikeyMJCO** [comment]
> @MikeyMJCO so I find this confusing as a mac & occassionally windows buildkit user. It implies there is no support for either. For windows I have only used in vagrant so that might be true but for Mac there are no obvious support issues

Pushed a change to address - better?

**Comment by eileenmcnaughton** [comment]
Yes - that looks good @MikeyMJCO - maybe @demeritcowboy has more comments re buildkit on a mac

**Comment by demeritcowboy** [comment]
str_replace('mac', 'windows', $this->getPreviousComment());

**Comment by MikeyMJCO** [comment]
lol :-D

I'm gonna wait for review by @totten on this one before merging :-)

**Comment by totten** [comment]
@MikeyMJCO I agree it's useful to give a specific list of supported/unsupported versions for people looking at boundary cases. (*Is my version from Ubuntu X.10 too new because it just came out? Is my EOL release still OK?*) But the full table feels like... a lot of information that most readers don't need to read. The TLDR is that release should be *recent/supported*.

I pushed a proposed update. What do you think of tweaking the text to put more emphasis on recent/supported and using a hyperlink to define?

**Comment by MikeyMJCO** [comment]
Yeah - that's better - stick it as an appendix at the end of the page - good calL!

**Comment by seamuslee001** [comment]
changes are ok by me

**Pull request merged**
