### PR TITLE
Update custom data for apiv4 mentioning the class used for OOP coding…

### PR DESCRIPTION
**Pull request by seamuslee001**
… format for Multi Record Custom data sets

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @colemanw @MikeyMJCO

**Comment by colemanw** [comment]
@seamuslee001 I made some edits, see what you think.

**Comment by seamuslee001** [comment]
changes look fine to me @colemanw thoughts @MikeyMJCO ?

**Comment by MikeyMJCO** [comment]
Looks great to me - merging!

**Pull request merged**
