### PR TITLE
Tweak api architecture & changelog and move hook changelog to its own page

### PR DESCRIPTION
**Pull request by colemanw**
The big change here is to move the hook changelog to its own page since it does not belong with APIv3.

### CODE REVIEW

**Comment by colemanw** [comment]
@MikeyMJCO see if you agree with this reorganization

**Comment by colemanw** [comment]
@eileenmcnaughton you might also have an opinion about moving hook changes to a separate page.

**Comment by MikeyMJCO** [comment]
This looks very good to me in principle. I haven't done an in-depth content review but I'm okay with the reorganisation aspect!

**Comment by eileenmcnaughton** [comment]
Makes sense I guess - I don't have a strong opinion here as long as it's easy to find

**Pull request merged**
