### PR TITLE
Contributing to core - adapted my email rant

### PR DESCRIPTION
**Pull request by agh1**
I had written a note on the civicrm-dev list about how to name and work with Jira issues, and I was encouraged to adapt it for the docs.

### CODE REVIEW

**Comment by seanmadsen** [comment]
Hey @agh1 this looks awesome, but I haven't read over all the changes yet.

I'm curious: did you happen to notice that issue [#61](https://github.com/civicrm/civicrm-dev-docs/issues/61) is saying we should migrate content from `civicrm-core/.github/CONTRIBUTING.md` as well as the wiki pages on [Git commit messages](https://wiki.civicrm.org/confluence/display/CRMDOC/Git+Commit+Messages+for+CiviCRM) and [Contributing](https://wiki.civicrm.org/confluence/display/CRMDOC/Contributing+to+CiviCRM+using+GitHub), and this [blog post](http://blogs.atlassian.com/2016/07/written-unwritten-guide-pull-requests/)? &mdash; I'm just wondering how much I should look over those sources as well when looking at this PR.

**Comment by agh1** [comment]
I didn't see #61--a few folks had suggested I put the email in the docs, and @ErichBSchulz suggested that it be the intro for the Contributing section.  I wrote the piece with that in mind.

Despite how long it is, I was actually trying to give more of an overview than a deep dive on pull-request statuses, commit messages, or anything else.  What I would propose is:

- link to `civicrm-core/blob/master/.github/CONTRIBUTING.md` from this piece when it discusses pull requests
- the commit messages wiki page is linked; when it migrates to MkDocs, update the link
- slice and dice [Contributing to CiviCRM using GitHub](https://wiki.civicrm.org/confluence/display/CRMDOC/Contributing+to+CiviCRM+using+GitHub) to go to a few places in MkDocs, including this page, the commit messages page, and [Codebase & Architecture](https://docs.civicrm.org/dev/en/master/core/architecture/)
- linking to that blog post somewhere and make sure important concepts are covered in our docs

**Comment by seanmadsen** [comment]
@agh1 I made two edits when previewing your changes locally: 

1. 2fe5e2c3ae72600cc8f125dfaf234a82afb2aa0e removed preceding slash from page path in `mkdocs.yml`. I can see how this slash ended up there -- because I put slashes in all those *comments* (whoops, I'll fix that :sheep:)
1. 21574df7ba82c8af9a2db4049313abc62ad998ba removed `/docs` from internal URLs. I will clarify the need for this in the meta docs

**Question** for you: as you edit, are you previewing locally with `mkdocs`? Because if so, I'm surprised that the site built successfully for you without the first change above -- *and if not*, then you might like to try it, because it's pretty awesome. [Steps here](https://docs.civicrm.org/dev/en/master/documentation/#editing-locally-with-mkdocs).

**Comment by seanmadsen** [comment]
Also @agh1 I did a10d0b6a2fcc5511c69e2f4155531d9fdb2eaf14 to remove the list you wrote at the top of the page -- since every item in that list is a heading, readers already get the list by looking at the TOC nav on the right side of the page.

**Pull request merged**
