### PR TITLE
Document extension dependencies in info.xml

### PR DESCRIPTION
**Pull request by seanmadsen**
This PR depends on https://github.com/civicrm/civicrm-core/pull/11101

### CODE REVIEW

**Comment by seanmadsen** [comment]
@JohnFF any interest in reviewing this?

**Comment by JohnFF** [comment]
OK will do

**Comment by JohnFF** [comment]
Hi @seanmadsen, in my view it should explicitly use the example as given in the PR. 

<requires>
  <ext>com.civifirst.dependency1</ext>
  <ext>com.civifirst.dependency2</ext>
</requires>

Cheers

**Comment by seanmadsen** [comment]
Thanks @JohnFF I added an example.

**Pull request merged**
