### PR TITLE
(WIP) CRM-18792 - Add theming guide

### PR DESCRIPTION
**Pull request by totten**
Depends on https://github.com/civicrm/civicrm-core/pull/8523

### CODE REVIEW

**Comment by ErichBSchulz** [comment]
how come this hasn't been merged?

**Comment by michaelmcandrew** [comment]
looks like https://github.com/civicrm/civicrm-core/pull/8523 is still open - might be the reason

**Comment by ErichBSchulz** [comment]
oh right

**Comment by totten** [comment]
Related: https://github.com/civicrm/org.civicrm.shoreditch/issues/3

**Comment by seanmadsen** [comment]
@totten It looks like the [core PR](https://github.com/civicrm/civicrm-core/pull/8523) on which these changes depend [was abandoned](https://github.com/civicrm/civicrm-core/pull/8523#issuecomment-305938979). Can we close this PR? Or is there useful content in here that you think we should get into the Developer Guide? I'll close this PR in one week if I don't hear anything.

**Comment by seanmadsen** [comment]
I'm closing this PR now due to the combination of the following things: 

* The core PR was closed
* In the core PR it looks like Eileen had trouble getting a response from @totten when asking if it was okay to close
* I gave @totten 1 week to respond and didn't hear anything
* We can re-open if needed

**Pull request closed without merging**
