### PR TITLE
(Repost) Clarify how to use anchor links with ts

### PR DESCRIPTION
**Pull request by demeritcowboy**
Repost of PR #751 which got borked by #755

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Thanks! Just as an FYI which might be related to the upgrades, I received the merged notification email three times. Or maybe it's because it was closed and reopened but it's sending a merged notice when somebody closes and another merged notice when reopened?

**Comment by MikeyMJCO** [comment]
Thanks - I'll keep an eye on it - I only got it once - but I'll log the mails for a few weeks and keep an eye on it!

**Comment by demeritcowboy** [comment]
Ok. And just noticing it doesn't seem to be live? Does it only batch process daily or so?

**Comment by MikeyMJCO** [comment]
It should be processing them immediately - it appears to be getting caught up on clearing a cache folder. Looking into it!

**Pull request merged**
