### PR TITLE
Remove reference on how to hack with how to fix

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
We have a template for how to fix core files to support this hook properly. This commit points people to it.

### CODE REVIEW

**Comment by seanmadsen** [comment]
Thanks @eileenmcnaughton!

**Comment by seanmadsen** [comment]
No, you made a PR. I just merged it very quickly :slightly_smiling_face:

**Comment by seanmadsen** [comment]
With simple PRs like this I just give them a quick look.

**Comment by eileenmcnaughton** [comment]
ah thanks - so quick you confused me!

**Pull request merged**
