### PR TITLE
Create hook_civicrm_customPre.md

### PR DESCRIPTION
**Pull request by lcdservices**
documentation to accompany PR 17144

### CODE REVIEW

**Comment by MikeyMJCO** [comment]
Need to update the hooks list page as well. Is this open to maintainer commits so I can run the regen script?

**Comment by lcdservices** [comment]
here's a second PR for that page: https://github.com/civicrm/civicrm-dev-docs/pull/827

**Comment by seamuslee001** [comment]
@MikeyMJCO @lcdservices I have pushed the change necessary here, I also fixed some issues with the script for generating the summary index of hooks at the same time mainly due to the recent mkdocs upgrades

**Comment by MikeyMJCO** [comment]
Thanks Seamus!

**Pull request merged**
