### PR TITLE
Update buildkit.md

### PR DESCRIPTION
**Pull request by dvhirst**
Edit to paragraph format rather than short lines.

### CODE REVIEW

**Comment by dvhirst** [comment]
I'm reading for content, and editing for consistency.  If you'd prefer that I just read for content; let me know...

**Comment by seanmadsen** [comment]
Consistency is great!

**Comment by dvhirst** [comment]
I'm reading for content and editing for consistency; if you'd prefer that I just read for content, let me know...

**Comment by dvhirst** [comment]
OK, you've got it.

**Pull request merged**
