### PR TITLE
Add in style guidelines on writing shell documentation as per isuse #…

### PR DESCRIPTION
**Pull request by seamuslee001**
…#190 proposal

ping @totten @MegaphoneJon @seanmadsen @nganivet I think Sean's latest proposal on this issue is good so have written documentation based on that but if we need more discussion best go on the issue

### CODE REVIEW

**Comment by seanmadsen** [comment]
:+1: I like this. Will wait to merge until we have more approvals from others.

**Comment by nganivet** [comment]
+1, very sound and clearly written.

**Comment by MegaphoneJon** [comment]
This sounds good.

**Comment by seamuslee001** [comment]
@seanmadsen seems like we have consensus here

**Pull request merged**
